const messages=document.getElementById('messages'),form=document.getElementById('composer'),input=document.getElementById('input'),sessionInput=document.getElementById('session'),send=document.getElementById('send'),statusText=document.getElementById('statusText'),statusDot=document.getElementById('statusDot');
const skillsEl=document.getElementById('skills'),toolsEl=document.getElementById('tools'),skillCount=document.getElementById('skillCount'),toolCount=document.getElementById('toolCount');
const subagentsEl=document.getElementById('subagents'),createSubagent=document.getElementById('createSubagent'),subagentModal=document.getElementById('subagentModal'),closeSubagent=document.getElementById('closeSubagent'),cancelSubagent=document.getElementById('cancelSubagent'),subagentForm=document.getElementById('subagentForm'),subagentName=document.getElementById('subagentName'),subagentDescription=document.getElementById('subagentDescription'),subagentPrompt=document.getElementById('subagentPrompt'),subagentError=document.getElementById('subagentError');
function addMessage(role,text=''){document.querySelector('.welcome')?.remove();const row=document.createElement('div');row.className=`msg ${role}`;const avatar=document.createElement('div');avatar.className='avatar';avatar.textContent=role==='user'?'YOU':'λ';const bubble=document.createElement('div');bubble.className='bubble';bubble.textContent=text;row.append(avatar,bubble);messages.appendChild(row);messages.scrollTop=messages.scrollHeight;return bubble}
async function health(){try{const r=await fetch('/health');if(!r.ok)throw 0;statusDot.classList.add('ok');statusText.textContent='Gateway connected'}catch{statusDot.classList.remove('ok');statusText.textContent='Gateway unavailable'}}
function capabilityCard(item,type){const el=document.createElement('button');el.className='capability';const name=document.createElement('strong');name.textContent=item.name;const desc=document.createElement('span');desc.textContent=type==='skill'?(item.description||item.instructions||'Skill'):(item.description||'Tool');el.append(name,desc);if(type==='skill'&&item.tags?.length){const tags=document.createElement('small');tags.textContent=item.tags.slice(0,3).join(' · ');el.append(tags)}if(type==='tool'&&item.input_schema){el.title='Click to insert an example tool request';el.addEventListener('click',()=>{input.value=`Use the UTCP tool "${item.name}". Provide the required arguments and show the result.`;input.focus();input.dispatchEvent(new Event('input'))})}return el}
async function loadCapabilities(){try{const [sr,tr]=await Promise.all([fetch('/api/skills'),fetch('/api/tools')]);if(!sr.ok||!tr.ok)throw 0;const skills=(await sr.json()).skills||[],tools=(await tr.json()).tools||[];skillCount.textContent=skills.length;toolCount.textContent=tools.length;skillsEl.replaceChildren(...skills.map(x=>capabilityCard(x,'skill')));toolsEl.replaceChildren(...tools.map(x=>capabilityCard(x,'tool')));if(!skills.length)skillsEl.innerHTML='<div class="empty">No enabled skills</div>';if(!tools.length)toolsEl.innerHTML='<div class="empty">No registered tools</div>'}catch{skillsEl.innerHTML='<div class="empty">Unavailable</div>';toolsEl.innerHTML='<div class="empty">Unavailable</div>'}}
function subagentCard(item){const el=document.createElement('button');el.className='capability subagent';const name=document.createElement('strong');name.textContent=item.name;const desc=document.createElement('span');desc.textContent=item.description||'UTCP sub-agent';el.append(name,desc);el.addEventListener('click',()=>{input.value=`Delegate this task to the ${item.name} sub-agent.`;input.focus();input.dispatchEvent(new Event('input'))});return el}
async function loadSubagents(){try{const r=await fetch('/api/subagents');if(!r.ok)throw 0;const items=(await r.json()).subagents||[];subagentsEl.replaceChildren(...items.map(subagentCard));if(!items.length)subagentsEl.innerHTML='<div class="empty">No sub-agents yet</div>'}catch{subagentsEl.innerHTML='<div class="empty">Unavailable</div>'}}
function openSubagentModal(){subagentError.textContent='';subagentForm.reset();subagentModal.classList.remove('hidden');setTimeout(()=>subagentName.focus(),0)}
function closeSubagentModal(){subagentModal.classList.add('hidden')}
async function submitSubagent(e){e.preventDefault();subagentError.textContent='';const payload={name:subagentName.value.trim(),description:subagentDescription.value.trim(),system_prompt:subagentPrompt.value.trim()};if(!payload.name)return;const button=subagentForm.querySelector('button[type="submit"]');button.disabled=true;try{const r=await fetch('/api/subagents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw Error(data.error||`Request failed (${r.status})`);closeSubagentModal();await loadSubagents();input.value=`Use the ${data.name} sub-agent for the next task.`;input.focus();input.dispatchEvent(new Event('input'))}catch(e){subagentError.textContent=e.message}finally{button.disabled=false}}
async function streamChat(session,message,bubble){const r=await fetch('/stream',{method:'POST',headers:{'Content-Type':'application/json','Accept':'text/event-stream'},body:JSON.stringify({session,message})});if(!r.ok){let d=`Request failed (${r.status})`;try{d=(await r.json()).error||d}catch{}throw Error(d)}if(!r.body)throw Error('Streaming is not supported by this browser');const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split(/\n\n/);buffer=events.pop()||'';for(const event of events)for(const line of event.split('\n')){if(!line.startsWith('data: '))continue;const data=line.slice(6);if(!data)continue;try{const payload=JSON.parse(data);if(payload.error)throw Error(payload.error);if(payload.delta)bubble.textContent+=payload.delta;if(payload.done)return}catch(e){if(e instanceof Error)throw e;bubble.textContent+=data}messages.scrollTop=messages.scrollHeight}}}
async function submit(message){message=message.trim();if(!message||send.disabled)return;const session=sessionInput.value.trim()||'web';input.value='';input.style.height='auto';addMessage('user',message);const bubble=addMessage('assistant');send.disabled=true;input.disabled=true;try{await streamChat(session,message,bubble)}catch(e){bubble.textContent=`Error: ${e.message}`}finally{send.disabled=false;input.disabled=false;input.focus()}}
form.addEventListener('submit',e=>{e.preventDefault();submit(input.value)});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});input.addEventListener('input',()=>{input.style.height='auto';input.style.height=`${Math.min(input.scrollHeight,180)}px`});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.prompt;input.focus();input.dispatchEvent(new Event('input'))}));
createSubagent?.addEventListener('click',openSubagentModal);closeSubagent?.addEventListener('click',closeSubagentModal);cancelSubagent?.addEventListener('click',closeSubagentModal);subagentModal?.addEventListener('click',e=>{if(e.target===subagentModal)closeSubagentModal()});subagentForm?.addEventListener('submit',submitSubagent);
health();loadCapabilities();loadSubagents();setInterval(health,15000);setInterval(loadCapabilities,30000);setInterval(loadSubagents,10000);
