const CodeModeUI = (() => {
  const state = { nodes: [], active: null, sequence: 0, sawEvent: false };
  function ensurePanel(){let p=document.getElementById('codemodeWorkflow');if(p)return p;p=document.createElement('section');p.id='codemodeWorkflow';p.className='codemode-workflow hidden';p.innerHTML='<div class="codemode-header"><div><span class="codemode-eyebrow">CODEMODE</span><strong>Tool workflow</strong></div><span id="codemodeStatus" class="codemode-status">idle</span></div><div id="codemodeGraph" class="codemode-graph"></div>';document.getElementById('messages')?.prepend(p);return p}
  function setStatus(t,k=''){const e=document.getElementById('codemodeStatus');if(!e)return;e.textContent=t;e.className=`codemode-status ${k}`.trim()}
  function render(){const p=ensurePanel();p.classList.remove('hidden');const g=document.getElementById('codemodeGraph');if(!g)return;g.replaceChildren(...state.nodes.map((n,i)=>{const w=document.createElement('div');w.className='codemode-node-wrap';if(i){const e=document.createElement('div');e.className='codemode-edge';e.innerHTML='<span>↓</span>';w.append(e)}const c=document.createElement('article');c.className=`codemode-node ${n.status||''}`.trim();const h=document.createElement('div');h.className='codemode-node-head';const m=document.createElement('span');m.className='codemode-node-marker';m.textContent=n.status==='done'?'✓':n.status==='error'?'!':n.status==='running'?'●':String(i+1);const t=document.createElement('div');t.className='codemode-node-title';const s=document.createElement('strong');s.textContent=n.title;const meta=document.createElement('span');meta.textContent=n.tool;t.append(s,meta);const b=document.createElement('span');b.className='codemode-node-badge';b.textContent=n.status;h.append(m,t,b);const d=document.createElement('div');d.className='codemode-node-details';if(n.args){const a=document.createElement('pre');a.className='codemode-code';a.textContent=JSON.stringify(n.args,null,2);d.append(a)}if(n.output){const o=document.createElement('pre');o.className='codemode-output';o.textContent=n.output;d.append(o)}if(n.duration){const x=document.createElement('span');x.className='codemode-duration';x.textContent=n.duration;d.append(x)}c.append(h,d);w.append(c);return w}))}
  function addNode(title,tool){const n={id:`codemode-${++state.sequence}`,title,tool,status:'running',startedAt:performance.now()};state.nodes.push(n);state.active=n;setStatus(`${state.nodes.length} node${state.nodes.length===1?'':'s'} · running`,'running');render();return n}
  function finishNode(out=''){if(!state.active)return;state.active.status='done';state.active.output=out;state.active.duration=`${Math.max(1,Math.round(performance.now()-state.active.startedAt))} ms`;state.active=null;setStatus(`${state.nodes.length} node${state.nodes.length===1?'':'s'} · complete`,'done');render()}
  function fail(msg){if(state.active){state.active.status='error';state.active.output=msg;state.active.duration=`${Math.max(1,Math.round(performance.now()-state.active.startedAt))} ms`;state.active=null}setStatus('workflow failed','error');render()}
  function reset(){state.nodes.length=0;state.active=null;state.sawEvent=false;ensurePanel().classList.add('hidden');setStatus('idle')}
  function onToolEvent(e){if(!e?.type||!e.tool)return;state.sawEvent=true;if(e.type==='codemode_tool_start'){const n=addNode(`Execute ${e.tool}`,e.tool);n.args=e.args;render();return}const n=state.nodes.find(x=>x.tool===e.tool&&x.status==='running')||state.active;if(!n)return;n.duration=`${Math.max(1,Number(e.duration_ms||0))} ms`;if(e.type==='codemode_tool_error'){n.status='error';n.output=e.error||'Tool execution failed';if(state.active===n)state.active=null;setStatus('workflow failed','error');render();return}if(e.type==='codemode_tool_result'){n.status='done';n.output=typeof e.result==='string'?e.result:JSON.stringify(e.result,null,2);if(state.active===n)state.active=null;setStatus(`${state.nodes.length} node${state.nodes.length===1?'':'s'} · complete`,'done');render()}}
  function inspectToolPanel(panel){const title=panel.querySelector('.tool-activity-title')?.textContent||'';const match=title.match(/apply tool\s+(.+)/i);if(!match||state.sawEvent)return;const tool=match[1].trim();const output=panel.querySelector('.tool-activity-output')?.textContent||'';if(!state.active)addNode(`Execute ${tool}`,tool);if(state.active&&output&&output!=='Running…'&&output!=='No output returned')finishNode(output)}
  function observe(){const messages=document.getElementById('messages');if(!messages)return;const observer=new MutationObserver(m=>{for(const x of m)for(const n of x.addedNodes){if(!(n instanceof Element))continue;n.querySelectorAll?.('.tool-activity').forEach(inspectToolPanel);if(n.matches?.('.tool-activity'))inspectToolPanel(n)}messages.querySelectorAll('.tool-activity').forEach(inspectToolPanel)});observer.observe(messages,{childList:true,subtree:true,characterData:true})}
  function hookComposer(){document.getElementById('composer')?.addEventListener('submit',reset,{capture:true})}
  function init(){ensurePanel();observe();hookComposer()}
  return {init,reset,addNode,finishNode,fail,onToolEvent};
})();
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>CodeModeUI.init()):CodeModeUI.init();
